// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0
// 	protoc        v3.13.0
// source: common.proto

package oz

import (
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type LeaderboardType_T int32

const (
	LeaderboardType_NONE      LeaderboardType_T = 0
	LeaderboardType_STAGE     LeaderboardType_T = 1 // 클리어 스테이지 수
	LeaderboardType_CHARACTER LeaderboardType_T = 2 // 보유 캐릭터 수
	LeaderboardType_MAX       LeaderboardType_T = 3
)

// Enum value maps for LeaderboardType_T.
var (
	LeaderboardType_T_name = map[int32]string{
		0: "NONE",
		1: "STAGE",
		2: "CHARACTER",
		3: "MAX",
	}
	LeaderboardType_T_value = map[string]int32{
		"NONE":      0,
		"STAGE":     1,
		"CHARACTER": 2,
		"MAX":       3,
	}
)

func (x LeaderboardType_T) Enum() *LeaderboardType_T {
	p := new(LeaderboardType_T)
	*p = x
	return p
}

func (x LeaderboardType_T) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (LeaderboardType_T) Descriptor() protoreflect.EnumDescriptor {
	return file_common_proto_enumTypes[0].Descriptor()
}

func (LeaderboardType_T) Type() protoreflect.EnumType {
	return &file_common_proto_enumTypes[0]
}

func (x LeaderboardType_T) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use LeaderboardType_T.Descriptor instead.
func (LeaderboardType_T) EnumDescriptor() ([]byte, []int) {
	return file_common_proto_rawDescGZIP(), []int{0, 0}
}

type LeaderboardUpdateStatus_T int32

const (
	LeaderboardUpdateStatus_NONE      LeaderboardUpdateStatus_T = 0
	LeaderboardUpdateStatus_NEW       LeaderboardUpdateStatus_T = 1
	LeaderboardUpdateStatus_CHANGED   LeaderboardUpdateStatus_T = 2
	LeaderboardUpdateStatus_UNCHANGED LeaderboardUpdateStatus_T = 3
	LeaderboardUpdateStatus_MAX       LeaderboardUpdateStatus_T = 4
)

// Enum value maps for LeaderboardUpdateStatus_T.
var (
	LeaderboardUpdateStatus_T_name = map[int32]string{
		0: "NONE",
		1: "NEW",
		2: "CHANGED",
		3: "UNCHANGED",
		4: "MAX",
	}
	LeaderboardUpdateStatus_T_value = map[string]int32{
		"NONE":      0,
		"NEW":       1,
		"CHANGED":   2,
		"UNCHANGED": 3,
		"MAX":       4,
	}
)

func (x LeaderboardUpdateStatus_T) Enum() *LeaderboardUpdateStatus_T {
	p := new(LeaderboardUpdateStatus_T)
	*p = x
	return p
}

func (x LeaderboardUpdateStatus_T) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (LeaderboardUpdateStatus_T) Descriptor() protoreflect.EnumDescriptor {
	return file_common_proto_enumTypes[1].Descriptor()
}

func (LeaderboardUpdateStatus_T) Type() protoreflect.EnumType {
	return &file_common_proto_enumTypes[1]
}

func (x LeaderboardUpdateStatus_T) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use LeaderboardUpdateStatus_T.Descriptor instead.
func (LeaderboardUpdateStatus_T) EnumDescriptor() ([]byte, []int) {
	return file_common_proto_rawDescGZIP(), []int{1, 0}
}

type TemplateEnum_T int32

const (
	TemplateEnum_NONE   TemplateEnum_T = 0
	TemplateEnum_FIRST  TemplateEnum_T = 1
	TemplateEnum_SECOND TemplateEnum_T = 2
	TemplateEnum_MAX    TemplateEnum_T = 3
)

// Enum value maps for TemplateEnum_T.
var (
	TemplateEnum_T_name = map[int32]string{
		0: "NONE",
		1: "FIRST",
		2: "SECOND",
		3: "MAX",
	}
	TemplateEnum_T_value = map[string]int32{
		"NONE":   0,
		"FIRST":  1,
		"SECOND": 2,
		"MAX":    3,
	}
)

func (x TemplateEnum_T) Enum() *TemplateEnum_T {
	p := new(TemplateEnum_T)
	*p = x
	return p
}

func (x TemplateEnum_T) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TemplateEnum_T) Descriptor() protoreflect.EnumDescriptor {
	return file_common_proto_enumTypes[2].Descriptor()
}

func (TemplateEnum_T) Type() protoreflect.EnumType {
	return &file_common_proto_enumTypes[2]
}

func (x TemplateEnum_T) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TemplateEnum_T.Descriptor instead.
func (TemplateEnum_T) EnumDescriptor() ([]byte, []int) {
	return file_common_proto_rawDescGZIP(), []int{3, 0}
}

// Leaderboard
type LeaderboardType struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *LeaderboardType) Reset() {
	*x = LeaderboardType{}
	if protoimpl.UnsafeEnabled {
		mi := &file_common_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LeaderboardType) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LeaderboardType) ProtoMessage() {}

func (x *LeaderboardType) ProtoReflect() protoreflect.Message {
	mi := &file_common_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LeaderboardType.ProtoReflect.Descriptor instead.
func (*LeaderboardType) Descriptor() ([]byte, []int) {
	return file_common_proto_rawDescGZIP(), []int{0}
}

type LeaderboardUpdateStatus struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *LeaderboardUpdateStatus) Reset() {
	*x = LeaderboardUpdateStatus{}
	if protoimpl.UnsafeEnabled {
		mi := &file_common_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LeaderboardUpdateStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LeaderboardUpdateStatus) ProtoMessage() {}

func (x *LeaderboardUpdateStatus) ProtoReflect() protoreflect.Message {
	mi := &file_common_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LeaderboardUpdateStatus.ProtoReflect.Descriptor instead.
func (*LeaderboardUpdateStatus) Descriptor() ([]byte, []int) {
	return file_common_proto_rawDescGZIP(), []int{1}
}

type OZRanker struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Uid      string `protobuf:"bytes,1,opt,name=uid,proto3" json:"uid,omitempty"`                            // 유저 아이디
	Rank     int64  `protobuf:"varint,2,opt,name=rank,proto3" json:"rank,omitempty"`                         // 랭크
	Score    int64  `protobuf:"varint,3,opt,name=score,proto3" json:"score,omitempty"`                       // 점수
	UpdateAt int32  `protobuf:"varint,4,opt,name=update_at,json=updateAt,proto3" json:"update_at,omitempty"` // 갱신 시간
}

func (x *OZRanker) Reset() {
	*x = OZRanker{}
	if protoimpl.UnsafeEnabled {
		mi := &file_common_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *OZRanker) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OZRanker) ProtoMessage() {}

func (x *OZRanker) ProtoReflect() protoreflect.Message {
	mi := &file_common_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OZRanker.ProtoReflect.Descriptor instead.
func (*OZRanker) Descriptor() ([]byte, []int) {
	return file_common_proto_rawDescGZIP(), []int{2}
}

func (x *OZRanker) GetUid() string {
	if x != nil {
		return x.Uid
	}
	return ""
}

func (x *OZRanker) GetRank() int64 {
	if x != nil {
		return x.Rank
	}
	return 0
}

func (x *OZRanker) GetScore() int64 {
	if x != nil {
		return x.Score
	}
	return 0
}

func (x *OZRanker) GetUpdateAt() int32 {
	if x != nil {
		return x.UpdateAt
	}
	return 0
}

type TemplateEnum struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *TemplateEnum) Reset() {
	*x = TemplateEnum{}
	if protoimpl.UnsafeEnabled {
		mi := &file_common_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TemplateEnum) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TemplateEnum) ProtoMessage() {}

func (x *TemplateEnum) ProtoReflect() protoreflect.Message {
	mi := &file_common_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TemplateEnum.ProtoReflect.Descriptor instead.
func (*TemplateEnum) Descriptor() ([]byte, []int) {
	return file_common_proto_rawDescGZIP(), []int{3}
}

type OZTemplate struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id    string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Count int64  `protobuf:"varint,2,opt,name=count,proto3" json:"count,omitempty"`
}

func (x *OZTemplate) Reset() {
	*x = OZTemplate{}
	if protoimpl.UnsafeEnabled {
		mi := &file_common_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *OZTemplate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OZTemplate) ProtoMessage() {}

func (x *OZTemplate) ProtoReflect() protoreflect.Message {
	mi := &file_common_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OZTemplate.ProtoReflect.Descriptor instead.
func (*OZTemplate) Descriptor() ([]byte, []int) {
	return file_common_proto_rawDescGZIP(), []int{4}
}

func (x *OZTemplate) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *OZTemplate) GetCount() int64 {
	if x != nil {
		return x.Count
	}
	return 0
}

var File_common_proto protoreflect.FileDescriptor

var file_common_proto_rawDesc = []byte{
	0x0a, 0x0c, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x02,
	0x6f, 0x7a, 0x22, 0x43, 0x0a, 0x0f, 0x4c, 0x65, 0x61, 0x64, 0x65, 0x72, 0x62, 0x6f, 0x61, 0x72,
	0x64, 0x54, 0x79, 0x70, 0x65, 0x22, 0x30, 0x0a, 0x01, 0x54, 0x12, 0x08, 0x0a, 0x04, 0x4e, 0x4f,
	0x4e, 0x45, 0x10, 0x00, 0x12, 0x09, 0x0a, 0x05, 0x53, 0x54, 0x41, 0x47, 0x45, 0x10, 0x01, 0x12,
	0x0d, 0x0a, 0x09, 0x43, 0x48, 0x41, 0x52, 0x41, 0x43, 0x54, 0x45, 0x52, 0x10, 0x02, 0x12, 0x07,
	0x0a, 0x03, 0x4d, 0x41, 0x58, 0x10, 0x03, 0x22, 0x56, 0x0a, 0x17, 0x4c, 0x65, 0x61, 0x64, 0x65,
	0x72, 0x62, 0x6f, 0x61, 0x72, 0x64, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x53, 0x74, 0x61, 0x74,
	0x75, 0x73, 0x22, 0x3b, 0x0a, 0x01, 0x54, 0x12, 0x08, 0x0a, 0x04, 0x4e, 0x4f, 0x4e, 0x45, 0x10,
	0x00, 0x12, 0x07, 0x0a, 0x03, 0x4e, 0x45, 0x57, 0x10, 0x01, 0x12, 0x0b, 0x0a, 0x07, 0x43, 0x48,
	0x41, 0x4e, 0x47, 0x45, 0x44, 0x10, 0x02, 0x12, 0x0d, 0x0a, 0x09, 0x55, 0x4e, 0x43, 0x48, 0x41,
	0x4e, 0x47, 0x45, 0x44, 0x10, 0x03, 0x12, 0x07, 0x0a, 0x03, 0x4d, 0x41, 0x58, 0x10, 0x04, 0x22,
	0x63, 0x0a, 0x08, 0x4f, 0x5a, 0x52, 0x61, 0x6e, 0x6b, 0x65, 0x72, 0x12, 0x10, 0x0a, 0x03, 0x75,
	0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x75, 0x69, 0x64, 0x12, 0x12, 0x0a,
	0x04, 0x72, 0x61, 0x6e, 0x6b, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x04, 0x72, 0x61, 0x6e,
	0x6b, 0x12, 0x14, 0x0a, 0x05, 0x73, 0x63, 0x6f, 0x72, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03,
	0x52, 0x05, 0x73, 0x63, 0x6f, 0x72, 0x65, 0x12, 0x1b, 0x0a, 0x09, 0x75, 0x70, 0x64, 0x61, 0x74,
	0x65, 0x5f, 0x61, 0x74, 0x18, 0x04, 0x20, 0x01, 0x28, 0x05, 0x52, 0x08, 0x75, 0x70, 0x64, 0x61,
	0x74, 0x65, 0x41, 0x74, 0x22, 0x3d, 0x0a, 0x0c, 0x54, 0x65, 0x6d, 0x70, 0x6c, 0x61, 0x74, 0x65,
	0x45, 0x6e, 0x75, 0x6d, 0x22, 0x2d, 0x0a, 0x01, 0x54, 0x12, 0x08, 0x0a, 0x04, 0x4e, 0x4f, 0x4e,
	0x45, 0x10, 0x00, 0x12, 0x09, 0x0a, 0x05, 0x46, 0x49, 0x52, 0x53, 0x54, 0x10, 0x01, 0x12, 0x0a,
	0x0a, 0x06, 0x53, 0x45, 0x43, 0x4f, 0x4e, 0x44, 0x10, 0x02, 0x12, 0x07, 0x0a, 0x03, 0x4d, 0x41,
	0x58, 0x10, 0x03, 0x22, 0x32, 0x0a, 0x0a, 0x4f, 0x5a, 0x54, 0x65, 0x6d, 0x70, 0x6c, 0x61, 0x74,
	0x65, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69,
	0x64, 0x12, 0x14, 0x0a, 0x05, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03,
	0x52, 0x05, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x42, 0x08, 0x50, 0x01, 0x5a, 0x04, 0x2e, 0x2f, 0x6f,
	0x7a, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_common_proto_rawDescOnce sync.Once
	file_common_proto_rawDescData = file_common_proto_rawDesc
)

func file_common_proto_rawDescGZIP() []byte {
	file_common_proto_rawDescOnce.Do(func() {
		file_common_proto_rawDescData = protoimpl.X.CompressGZIP(file_common_proto_rawDescData)
	})
	return file_common_proto_rawDescData
}

var file_common_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_common_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_common_proto_goTypes = []interface{}{
	(LeaderboardType_T)(0),          // 0: oz.LeaderboardType.T
	(LeaderboardUpdateStatus_T)(0),  // 1: oz.LeaderboardUpdateStatus.T
	(TemplateEnum_T)(0),             // 2: oz.TemplateEnum.T
	(*LeaderboardType)(nil),         // 3: oz.LeaderboardType
	(*LeaderboardUpdateStatus)(nil), // 4: oz.LeaderboardUpdateStatus
	(*OZRanker)(nil),                // 5: oz.OZRanker
	(*TemplateEnum)(nil),            // 6: oz.TemplateEnum
	(*OZTemplate)(nil),              // 7: oz.OZTemplate
}
var file_common_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_common_proto_init() }
func file_common_proto_init() {
	if File_common_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_common_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LeaderboardType); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_common_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LeaderboardUpdateStatus); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_common_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*OZRanker); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_common_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TemplateEnum); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_common_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*OZTemplate); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_common_proto_rawDesc,
			NumEnums:      3,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_common_proto_goTypes,
		DependencyIndexes: file_common_proto_depIdxs,
		EnumInfos:         file_common_proto_enumTypes,
		MessageInfos:      file_common_proto_msgTypes,
	}.Build()
	File_common_proto = out.File
	file_common_proto_rawDesc = nil
	file_common_proto_goTypes = nil
	file_common_proto_depIdxs = nil
}
